### PR TITLE
fix textFormField.dart line 877  Compilation error 

### PR DESCRIPTION
**Pull request by leeyisoft**
fix textFormField.dart line 877 Compilation error 

"The argument type 'bool?' can't be assigned to the parameter type 'bool'."

### CODE REVIEW

**Comment by dorklein** [comment]
I need the fix ASAP, It started to happen once I upgraded flutter to 3.16.0

**Review by dorklein — APPROVED** [review]
The changes sims to fix the problem

**Comment by leeyisoft** [comment]
It seems that the problem has been solved

**Comment by leeyisoft** [comment]
It seems that the problem has been solved

**Pull request closed without merging**
